---
title: "Fit Actual Parameters to Driver Quadrants"
output:
  html_document:
    df_print: paged
date: "2024-04-01"
---

# Load Data

```{r}
library(tidyverse)
library(mgcv)
library(kableExtra)
# load in data
df_st_club <- read_csv("/Users/zachstrennen/Documents/SquareFace_official_repo/2024-cmu/Data Cleaning/Output Data/Cleaned_Standard_Clubs.csv")

# Filter df for only drivers
df_driver_lim <- filter(df_st_club, Club == "7 Iron" & Sex == "Male")
df_driver_lim
```

# Models and Quantiles

```{r}
# Side model
driver_side_final <- gam::gam(`Max Height - Side` ~
                             gam::s(`Club Speed`) +
                             gam::s(`Attack Angle`) +
                             gam::s(`Swing Plane`) +
                             gam::s(`Face Angle`) +
                             gam::s(`Club Path`) +
                             gam::s(shaft_lean), data = df_driver_lim)

# Height model
driver_height_final <- gam::gam(`Max Height - Height` ~
                               gam::s(`Club Speed`) + 
                               gam::s(`Attack Angle`) + 
                               gam::s(`Swing Plane`) + 
                               gam::s(`Face Angle`) + 
                               gam::s(`Club Path`) + 
                               gam::s(shaft_lean), data = df_driver_lim)

# SPLIT THE DATA INTO QUARTERS
# First distance quartile
q1_dist <- quantile(df_driver_lim$`Est. Total Flat - Length`, 0.25)
# Second Distance quartile
median_dist <- quantile(df_driver_lim$`Est. Total Flat - Length`, 0.50)
# Third Distance quartile
q3_dist <- quantile(df_driver_lim$`Est. Total Flat - Length`, 0.75)


# SEVEN IRON .8
# Girls 7 iron 1

# 0-25% of data, divide height standard deviation by this
sd_divisor_side_1 <- 1
# 25-50% of data, divde height standard deviation by this
sd_divisor_side_2 <- 1
# 0-25% of data, divide height standard deviation by this
sd_divisor_side_3 <- 1
# 25-100% of data, divide height standard deviation by this
sd_divisor_side_4 <- 1

# Seven Iron 2
# Girls 7 iron 1

# 0-25% of data, divide height standard deviation by this
sd_divisor_height_1 <- 2
# 25-50% of data, divide height standard deviation by this
sd_divisor_height_2 <- 2
# 0-25% of data, divide height standard deviation by this
sd_divisor_height_3 <- 2
# 25-100% of data, divide height standard deviation by this
sd_divisor_height_4 <- 2
```

# Actual Side

```{r}
# Split for drivers and fades by sign
df_driver_lim$side_class_acc <- ifelse(df_driver_lim$`Max Height - Side` > 0, "Draw", "Fade")

# Limit data to first quartile
df_driver_lim_side1 <- filter(df_driver_lim, `Est. Total Flat - Length` < q1_dist)
# Get standard deviation
sd_lim_side1 <- sd(df_driver_lim_side1$`Max Height - Side`)

# Limit data to second quartile
df_driver_lim_side2 <- filter(df_driver_lim, `Est. Total Flat - Length` >= q1_dist)
df_driver_lim_side2 <- filter(df_driver_lim_side2, `Est. Total Flat - Length` < median_dist)
# Get standard deviation
sd_lim_side2 <- sd(df_driver_lim_side2$`Max Height - Side`)

# Limit data to third quartile
df_driver_lim_side3 <- filter(df_driver_lim, `Est. Total Flat - Length` >= median_dist)
df_driver_lim_side3 <- filter(df_driver_lim_side3, `Est. Total Flat - Length` < q3_dist)
# Get standard deviation
sd_lim_side3 <- sd(df_driver_lim_side3$`Max Height - Side`)

# Limit data to fourth quartile
df_driver_lim_side4 <- filter(df_driver_lim, `Est. Total Flat - Length` >= q3_dist)
# Get standard deviation
sd_lim_side4 <- sd(df_driver_lim_side4$`Max Height - Side`)

# Classify straights
for (i in 1:nrow(df_driver_lim)) {
  # Check to see if shot is in q1
  if (df_driver_lim[i, "Est. Total Flat - Length"] < q1_dist) {
    # Classify as straight is criteria is met
    if (df_driver_lim[i, "Max Height - Side"] < sd_lim_side1/sd_divisor_side_1 &
      df_driver_lim[i, "Max Height - Side"] > -sd_lim_side1/sd_divisor_side_1) {
      # Accessing the 'side_class' column by name to assign "Straight"
      df_driver_lim[i, "side_class_acc"] <- "Straight"
    }
    # Check to see if shot is in q2
  } else if (df_driver_lim[i, "Est. Total Flat - Length"] < median_dist) {
    # Classify as straight is criteria is met
    if (df_driver_lim[i, "Max Height - Side"] < sd_lim_side2/sd_divisor_side_2 &
      df_driver_lim[i, "Max Height - Side"] > -sd_lim_side2/sd_divisor_side_2) {
      df_driver_lim[i, "side_class_acc"] <- "Straight"
    }
    # Check to see if shot is in q3
  } else if (df_driver_lim[i, "Est. Total Flat - Length"] < q3_dist) {
    # Classify as straight is criteria is met
    if (df_driver_lim[i, "Max Height - Side"] < sd_lim_side3/sd_divisor_side_3 &
      df_driver_lim[i, "Max Height - Side"] > -sd_lim_side3/sd_divisor_side_3) {
      df_driver_lim[i, "side_class_acc"] <- "Straight"
    }
    # Check to see if shot is in q4
  } else {
    # Classify as straight is criteria is met
    if (df_driver_lim[i, "Max Height - Side"] < sd_lim_side4/sd_divisor_side_4 &
      df_driver_lim[i, "Max Height - Side"] > -sd_lim_side4/sd_divisor_side_4) {
      df_driver_lim[i, "side_class_acc"] <- "Straight"
    }
  }
}

hist(df_driver_lim$`Est. Total Flat - Length`, breaks=25, main="Distribution of Total Distance a Ball Travels\n(7 Irons - Males)", xlab = "Distance Traveld Forward (yds)", col="lightgrey")
abline(v = q1_dist, col="red", lty= 2)
abline(v = median_dist, col="red",lty= 2)
abline(v = q3_dist, col="red",lty= 2)
```

# Actual Height

```{r}
# Define height class variable
df_driver_lim$height_class_acc <- "Medium"

# Limit data to first quartile
df_driver_lim_height1 <- filter(df_driver_lim, `Est. Total Flat - Length` < q1_dist)
# Get mean and standard deviation
mean_lim_height1 <- mean(df_driver_lim_height1$`Max Height - Height`)
mean_lim_height1 <- 93
sd_lim_height1 <- sd(df_driver_lim_height1$`Max Height - Height`)

# Limit data to second quartile
df_driver_lim_height2 <- filter(df_driver_lim, `Est. Total Flat - Length` >= q1_dist)
df_driver_lim_height2 <- filter(df_driver_lim_height2, `Est. Total Flat - Length` < median_dist)
# Get mean and standard deviation
mean_lim_height2 <- mean(df_driver_lim_height2$`Max Height - Height`)
mean_lim_height2 <- 93
sd_lim_height2 <- sd(df_driver_lim_height2$`Max Height - Height`)

# Limit data to third quartile
df_driver_lim_height3 <- filter(df_driver_lim, `Est. Total Flat - Length` >= median_dist)
df_driver_lim_height3 <- filter(df_driver_lim_height3, `Est. Total Flat - Length` < q3_dist)
# Get mean and standard deviation
mean_lim_height3 <- mean(df_driver_lim_height3$`Max Height - Height`)
mean_lim_height3 <- 93
sd_lim_height3 <- sd(df_driver_lim_height3$`Max Height - Height`)

# Limit data to fourth quartile
df_driver_lim_height4 <- filter(df_driver_lim, `Est. Total Flat - Length` >= q3_dist)
# Get mean and standard deviation
mean_lim_height4 <- mean(df_driver_lim_height4$`Max Height - Height`)
mean_lim_height4 <- 93
sd_lim_height4 <- sd(df_driver_lim_height4$`Max Height - Height`)

# Classify height
for (i in 1:nrow(df_driver_lim)) {
  # Check if shot is in distance q1
  if (df_driver_lim[i, "Est. Total Flat - Length"] < q1_dist) {
    # Classify as high/low/medium based on criteria
    if (df_driver_lim[i, "Max Height - Height"] > (mean_lim_height1 + sd_lim_height1 / sd_divisor_height_1)) {
      df_driver_lim[i, "height_class_acc"] <- "High"
    }
    if (df_driver_lim[i, "Max Height - Height"] < (mean_lim_height1 - sd_lim_height1 / sd_divisor_height_1)) {
      df_driver_lim[i, "height_class_acc"] <- "Low"
    }
    # Check if shot is in distance q1
  } else if (df_driver_lim[i, "Est. Total Flat - Length"] < median_dist) {
    # Classify as high/low/medium based on criteria
    if (df_driver_lim[i, "Max Height - Height"] > (mean_lim_height2 + sd_lim_height2 / sd_divisor_height_2)) {
      df_driver_lim[i, "height_class_acc"] <- "High"
    }
    if (df_driver_lim[i, "Max Height - Height"] < (mean_lim_height2 - sd_lim_height2 / sd_divisor_height_2)) {
      df_driver_lim[i, "height_class_acc"] <- "Low"
    }
    # Check if shot is in distance q1
  } else if (df_driver_lim[i, "Est. Total Flat - Length"] < q3_dist) {
    # Classify as high/low/medium based on criteria
    if (df_driver_lim[i, "Max Height - Height"] > (mean_lim_height3 + sd_lim_height3 / sd_divisor_height_3)) {
      df_driver_lim[i, "height_class_acc"] <- "High"
    }
    if (df_driver_lim[i, "Max Height - Height"] < (mean_lim_height3 - sd_lim_height3 / sd_divisor_height_3)) {
      df_driver_lim[i, "height_class_acc"] <- "Low"
    }
    # Check if shot is in distance q1
  } else {
    # Classify as high/low/medium based on criteria
    if (df_driver_lim[i, "Max Height - Height"] > (mean_lim_height4 + sd_lim_height4 / sd_divisor_height_4)) {
      df_driver_lim[i, "height_class_acc"] <- "High"
    }
    if (df_driver_lim[i, "Max Height - Height"] < (mean_lim_height4 - sd_lim_height4 / sd_divisor_height_4)) {
      df_driver_lim[i, "height_class_acc"] <- "Low"
    }
  }
}
```

# View Distributions

```{r}
# Choose the shot shape you want to investigate
shot_shape_df <- filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "High")

par(mfrow= c(2,3))

# Create a histogram for all parameters of a chosen shot shape
hist(shot_shape_df$`Club Speed`, breaks = 10, main = "Club Speed", xlab = "Club Speed (mph)")
abline(v = median(shot_shape_df$`Club Speed`), col = "red", lty=2)
hist(shot_shape_df$`Attack Angle`, breaks = 10, main = "Attack Angle", xlab = "Attack Angle (degrees)")
abline(v = median(shot_shape_df$`Attack Angle`), col = "red", lty=2)
hist(shot_shape_df$`Swing Plane`, breaks = 10, main = "Swing Plane", xlab = "Swing Plane (degrees)")
abline(v = median(shot_shape_df$`Swing Plane`), col = "red", lty=2)
hist(shot_shape_df$`Face Angle`, breaks = 10, main = "Face Angle", xlab = "Face Angle (degrees)")
abline(v = median(shot_shape_df$`Face Angle`), col = "red", lty=2)
hist(shot_shape_df$`Club Path`, breaks = 10, main = "Club Path", xlab = "Club Path (degrees)")
abline(v = median(shot_shape_df$`Club Path`), col = "red", lty=2)
hist(shot_shape_df$shaft_lean, breaks = 10, main = "Shaft Lean", xlab = "Shaft Lean (degrees)")
abline(v = median(shot_shape_df$shaft_lean), col = "red", lty=2)
```

# Parameter Extraction

```{r}
# Create a data frame template to keep ideal parameters
df_ideal_driver <- data.frame(Club=character(), Height_Class=character(), Side_Class=character(),
                       Club_Path_Angle=double(), Lie_Angle=double(), Attack_Angle=double(),
                       Club_Speed=double(), Shaft_Lean=double(), Face_Angle=double())

# Lists for shot shapes
heights = c("High", "Medium", "Low")
sides = c("Draw", "Straight", "Fade")

# Variable for row iterator
row = 1

# Loop though each shot shape combination
for (height in heights){
    for (side in sides){
        # Filter to only specific shot shape
        shot_shape_df <- filter(df_driver_lim, side_class_acc == side & height_class_acc == height)
        
        # Store club and shot shape
        df_ideal_driver[row, "Club"] <- "Driver"
        df_ideal_driver[row, "Height_Class"] <- height
        df_ideal_driver[row, "Side_Class"] <- side
        
        # Get ideal parameters from medians
        df_ideal_driver[row, "Club_Path_Angle"] <- median(shot_shape_df$`Club Path`)
        df_ideal_driver[row, "Lie_Angle"] <- median(shot_shape_df$`Swing Plane`)
        df_ideal_driver[row, "Attack_Angle"] <- mean(shot_shape_df$`Attack Angle`)
        df_ideal_driver[row, "Club_Speed"] <- mean(shot_shape_df$`Club Speed`)
        df_ideal_driver[row, "Shaft_Lean"] <- mean(shot_shape_df$shaft_lean)
        df_ideal_driver[row, "Face_Angle"] <- mean(shot_shape_df$`Face Angle`)
        
        # Iterate to next row
        row = row + 1
    }
}

# Show data frame with ideal parameters
df_ideal_driver
```

# Fit and Visualtize

```{r}
# Create dummy data frame that matches with visualization
df_ideal_driver_mutated <- df_ideal_driver
colnames(df_ideal_driver_mutated) <- c("Club", "Height_Class", "Side_Class",
                                       "Club Path", "Swing Plane", "Attack Angle",
                                       "Club Speed", "shaft_lean", "Face Angle")

# Get predictions from moedls
side_preds <- predict(driver_side_final, df_ideal_driver_mutated)
height_preds <- predict(driver_height_final, df_ideal_driver_mutated)

# Data frame with predicted spot in air
predictions_quad <- data.frame(side_preds, height_preds)

# Get side means for each shot shape
side_mean <- c(
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "High")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "High")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "High")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Medium")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Medium")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Medium")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Low")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Low")$`Max Height - Side`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Low")$`Max Height - Side`)
              )

# Get height means for each shot shape
height_mean <- c(
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "High")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "High")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "High")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Medium")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Medium")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Medium")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Low")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Low")$`Max Height - Height`),
    mean(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Low")$`Max Height - Height`)
              )

shot_shape <- c("High Draw", "High Straight", "High Fade",
                "Medium Draw", "Medium Straight", "Medium Fade",
                "Low Draw", "Low Straight", "Low Fade")

# Put means in dataframe
means_quad <- data.frame(side_mean, height_mean)

par(mfrow = c(2, 2))
# Visualize q1 quadrants
ggplot(df_driver_lim_height1, aes(x = `Max Height - Side`, y = `Max Height - Height`)) +
    ylim(50,200) +
    xlim(-30,30) +
  geom_point(alpha = 0.5) +
  geom_vline(aes(xintercept = -sd_lim_side1/sd_divisor_side_1), col = "green") +
  geom_vline(aes(xintercept = sd_lim_side1/sd_divisor_side_1), col = "green")+
  geom_hline(aes(yintercept = (mean_lim_height1 + sd_lim_height1 / sd_divisor_height_1)), col = "green") +
  geom_hline(aes(yintercept = (mean_lim_height1 - sd_lim_height1 / sd_divisor_height_1)), col = "green") +
  theme(
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")
  ) +
  labs(
    title = "Distribution of Shots at Max Height for a Driver - Males",
    subtitle = "(Only for shots that fall within the first quartile of distance traveled)",
    y = "Height (ft)",
    x = "Side Distance (ft)"
  )

# Visualize q2 quadrants
ggplot(df_driver_lim_height2, aes(x = `Max Height - Side`, y = `Max Height - Height`)) +
    ylim(50,200) +
    xlim(-30,30) +
  geom_point(alpha = 0.5) +
  geom_vline(aes(xintercept = -sd_lim_side2/sd_divisor_side_2), col = "yellow") +
  geom_vline(aes(xintercept = sd_lim_side2/sd_divisor_side_2), col = "yellow")+
  geom_hline(aes(yintercept = (mean_lim_height2 + sd_lim_height2 / sd_divisor_height_2)), col = "yellow") +
  geom_hline(aes(yintercept = (mean_lim_height2 - sd_lim_height2 / sd_divisor_height_2)), col = "yellow") +
  theme(
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")
  ) +
  labs(
    title = "Distribution of Shots at Max Height for a Driver - Males",
    subtitle = "(Only for shots that fall within the first second of distance traveled)",
    y = "Height (ft)",
    x = "Side Distance (ft)"
  )

# Visualize q2 quadrants
ggplot(df_driver_lim_height3, aes(x = `Max Height - Side`, y = `Max Height - Height`)) +
    ylim(50,200) +
    xlim(-30,30) +
  geom_point(alpha = 0.5) +
  geom_vline(aes(xintercept = -sd_lim_side3/sd_divisor_side_3), col = "orange") +
  geom_vline(aes(xintercept = sd_lim_side3/sd_divisor_side_3), col = "orange")+
  geom_hline(aes(yintercept = (mean_lim_height3 + sd_lim_height3 / sd_divisor_height_3)), col = "orange") +
  geom_hline(aes(yintercept = (mean_lim_height3 - sd_lim_height3 / sd_divisor_height_3)), col = "orange") +
  theme(
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")
  ) +
  labs(
    title = "Distribution of Shots at Max Height for a Driver - Males",
    subtitle = "(Only for shots that fall within the third quartile of distance traveled)",
    y = "Height (ft)",
    x = "Side Distance (ft)"
  )


# Visualize q4 quadrants
ggplot(df_driver_lim_height4, aes(x = `Max Height - Side`, y = `Max Height - Height`)) +
    ylim(50,200) +
    xlim(-30,30) +
  geom_point(alpha = 0.5) +
  geom_vline(aes(xintercept = -sd_lim_side4/sd_divisor_side_4), col = "red") +
  geom_vline(aes(xintercept = sd_lim_side4/sd_divisor_side_4), col = "red")+
  geom_hline(aes(yintercept = (mean_lim_height4 + sd_lim_height4 / sd_divisor_height_4)), col = "red") +
  geom_hline(aes(yintercept = (mean_lim_height4 - sd_lim_height4 / sd_divisor_height_4)), col = "red") +
  theme(
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")
  ) +
  labs(
    title = "Distribution of Shots at Max Height for a Driver - Males",
    subtitle = "(Only for shots that fall within the fourth quartile of distance traveled)",
    y = "Height (ft)",
    x = "Side Distance (ft)"
  )

# Visualize all quadrants with the parameters landing via model
ggplot(df_driver_lim, aes(x = `Max Height - Side`, y = `Max Height - Height`)) +
  geom_point(alpha = 0.4) +
  geom_vline(aes(xintercept = -sd_lim_side1/sd_divisor_side_1), col = "green") +
  geom_vline(aes(xintercept = sd_lim_side1/sd_divisor_side_1), col = "green") +
  geom_vline(aes(xintercept = -sd_lim_side2/sd_divisor_side_2), col = "yellow") +
  geom_vline(aes(xintercept = sd_lim_side2/sd_divisor_side_2), col = "yellow") +
  geom_vline(aes(xintercept = -sd_lim_side3/sd_divisor_side_3), col = "orange") +
  geom_vline(aes(xintercept = sd_lim_side3/sd_divisor_side_3), col = "orange") +
  geom_vline(aes(xintercept = -sd_lim_side4/sd_divisor_side_4), col = "red") +
  geom_vline(aes(xintercept = sd_lim_side4/sd_divisor_side_4), col = "red") +
  geom_hline(aes(yintercept = (mean_lim_height1 + sd_lim_height1 / sd_divisor_height_1)), col = "green") +
  geom_hline(aes(yintercept = (mean_lim_height1 - sd_lim_height1 / sd_divisor_height_1)), col = "green") +
  geom_hline(aes(yintercept = (mean_lim_height2 + sd_lim_height2 / sd_divisor_height_2)), col = "yellow") +
  geom_hline(aes(yintercept = (mean_lim_height2 - sd_lim_height2 / sd_divisor_height_2)), col = "yellow") +
  geom_hline(aes(yintercept = (mean_lim_height3 + sd_lim_height3 / sd_divisor_height_3)), col = "orange") +
  geom_hline(aes(yintercept = (mean_lim_height3 - sd_lim_height3 / sd_divisor_height_3)), col = "orange") +
  geom_hline(aes(yintercept = (mean_lim_height4 + sd_lim_height4 / sd_divisor_height_4)), col = "red") +
  geom_hline(aes(yintercept = (mean_lim_height4 - sd_lim_height4 / sd_divisor_height_4)), col = "red") +
  labs(
    title = "Distribution of Shots at Max Height for a 7 Iron - Males",
    subtitle = "Shot shape quadrants dependent on the distance a ball travels",
    y = "Height (ft)",
    x = "Side Distance (ft)"
  ) +
    geom_text(x = -14, y = 135, label = "Fade") +
    geom_text(x = 0, y = 135, label = "Straight") +
    geom_text(x = 14, y = 135, label = "Draw") +
  theme(
    panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
    panel.background = element_blank(), axis.line = element_line(colour = "black")
  ) +
  geom_point(data = means_quad, aes(x = side_mean, y = height_mean), color = "violet", pch=20, size=10) +
  geom_point(data = predictions_quad, aes(x = side_preds, y = height_preds), color = "blue", pch=10, size=8)
```


```{r}
# Dummy df for sharing table
df_ideal_driver_sharable <- data.frame(
    Shot_Shape = paste(df_ideal_driver$Height_Class,df_ideal_driver$Side_Class),
    Club_Path_Angle = df_ideal_driver$Club_Path_Angle,
    Lie_Angle = df_ideal_driver$Lie_Angle,
    Attack_Angle = df_ideal_driver$Attack_Angle,
    Club_Speed = df_ideal_driver$Club_Speed,
    Shaft_Lean = df_ideal_driver$Shaft_Lean,
    Face_Angle = df_ideal_driver$Face_Angle)

# Output kable
kable(df_ideal_driver_sharable, escape = TRUE, caption = "Ideal Parameter Estimates for Driver From Centers of Actual Data") %>%
  kable_styling(latex_options = "hold_position")
```

# Getting Data Ranges

```{r}
# Get side sd for each shot shape
side_sd <- c(
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "High")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "High")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "High")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Medium")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Medium")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Medium")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Low")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Low")$`Max Height - Side`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Low")$`Max Height - Side`)
)

height_sd <- c(
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "High")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "High")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "High")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Medium")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Medium")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Medium")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Draw" & height_class_acc == "Low")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Straight" & height_class_acc == "Low")$`Max Height - Height`),
    sd(filter(df_driver_lim, side_class_acc == "Fade" & height_class_acc == "Low")$`Max Height - Height`)
)

range_df <- data.frame(shot_shape, side_mean, height_mean, side_sd, height_sd)

df_driver_ranged <- df_driver_lim

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "High") &
           (`Max Height - Height` > range_df[1,"height_mean"]+range_df[1,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "High") &
           (`Max Height - Height` < range_df[1,"height_mean"]-range_df[1,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "High") &
           (`Max Height - Side` > range_df[1,"side_mean"]+range_df[1,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "High") &
           (`Max Height - Side` < range_df[1,"side_mean"]-range_df[1,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "High") &
           (`Max Height - Height` > range_df[2,"height_mean"]+range_df[2,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "High") &
           (`Max Height - Height` < range_df[2,"height_mean"]-range_df[2,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "High") &
           (`Max Height - Side` > range_df[2,"side_mean"]+range_df[2,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "High") &
           (`Max Height - Side` < range_df[2,"side_mean"]-range_df[2,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "High") &
           (`Max Height - Height` > range_df[3,"height_mean"]+range_df[3,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "High") &
           (`Max Height - Height` < range_df[3,"height_mean"]-range_df[3,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "High") &
           (`Max Height - Side` > range_df[3,"side_mean"]+range_df[3,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "High") &
           (`Max Height - Side` < range_df[3,"side_mean"]-range_df[3,"side_sd"])))




df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Medium") &
           (`Max Height - Height` > range_df[4,"height_mean"]+range_df[4,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Medium") &
           (`Max Height - Height` < range_df[4,"height_mean"]-range_df[4,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Medium") &
           (`Max Height - Side` > range_df[4,"side_mean"]+range_df[4,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Medium") &
           (`Max Height - Side` < range_df[4,"side_mean"]-range_df[4,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Medium") &
           (`Max Height - Height` > range_df[5,"height_mean"]+range_df[5,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Medium") &
           (`Max Height - Height` < range_df[5,"height_mean"]-range_df[5,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Medium") &
           (`Max Height - Side` > range_df[5,"side_mean"]+range_df[5,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Medium") &
           (`Max Height - Side` < range_df[5,"side_mean"]-range_df[5,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Medium") &
           (`Max Height - Height` > range_df[6,"height_mean"]+range_df[6,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Medium") &
           (`Max Height - Height` < range_df[6,"height_mean"]-range_df[6,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Medium") &
           (`Max Height - Side` > range_df[6,"side_mean"]+range_df[6,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Medium") &
           (`Max Height - Side` < range_df[6,"side_mean"]-range_df[6,"side_sd"])))



df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Low") &
           (`Max Height - Height` > range_df[7,"height_mean"]+range_df[7,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Low") &
           (`Max Height - Height` < range_df[7,"height_mean"]-range_df[7,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Low") &
           (`Max Height - Side` > range_df[7,"side_mean"]+range_df[7,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Draw" & height_class_acc == "Low") &
           (`Max Height - Side` < range_df[7,"side_mean"]-range_df[7,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Low") &
           (`Max Height - Height` > range_df[8,"height_mean"]+range_df[8,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Low") &
           (`Max Height - Height` < range_df[8,"height_mean"]-range_df[8,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Low") &
           (`Max Height - Side` > range_df[8,"side_mean"]+range_df[8,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Straight" & height_class_acc == "Low") &
           (`Max Height - Side` < range_df[8,"side_mean"]-range_df[8,"side_sd"])))

df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Low") &
           (`Max Height - Height` > range_df[9,"height_mean"]+range_df[9,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Low") &
           (`Max Height - Height` < range_df[9,"height_mean"]-range_df[9,"height_sd"]/2)))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Low") &
           (`Max Height - Side` > range_df[9,"side_mean"]+range_df[9,"side_sd"])))
df_driver_ranged <- filter(df_driver_ranged, !((side_class_acc == "Fade" & height_class_acc == "Low") &
           (`Max Height - Side` < range_df[9,"side_mean"]-range_df[9,"side_sd"])))


# Choose the shot shape you want to investigate
shot_shape_df <- filter(df_driver_ranged, side_class_acc == "Fade" & height_class_acc == "Medium")

par(mfrow= c(2,3))

# Create a histogram for all parameters of a chosen shot shape
hist(shot_shape_df$`Club Speed`, breaks = 10, main = "Club Speed")
abline(v = median(shot_shape_df$`Club Speed`))
hist(shot_shape_df$`Attack Angle`, breaks = 10, main = "Attack Angle")
abline(v = median(shot_shape_df$`Attack Angle`))
hist(shot_shape_df$`Swing Plane`, breaks = 10, main = "Swing Plane")
abline(v = median(shot_shape_df$`Swing Plane`))
hist(shot_shape_df$`Face Angle`, breaks = 10, main = "Face Angle")
abline(v = median(shot_shape_df$`Face Angle`))
hist(shot_shape_df$`Club Path`, breaks = 10, main = "Club Path")
abline(v = median(shot_shape_df$`Club Path`))
hist(shot_shape_df$shaft_lean, breaks = 10, main = "Shaft Lean")
abline(v = median(shot_shape_df$shaft_lean))

# Create a data frame template to keep ideal parameters
df_ideal_driver_ranged <- data.frame(Club=character(), Height_Class=character(), Side_Class=character(),
                       Club_Path_Angle=double(), Lie_Angle=double(), Attack_Angle=double(),
                       Club_Speed=double(), Shaft_Lean=double(), Face_Angle=double())

# Lists for shot shapes
heights = c("High", "Medium", "Low")
sides = c("Draw", "Straight", "Fade")

# Variable for row iterator
row = 1

# Loop though each shot shape combination
for (height in heights){
    for (side in sides){
        # Filter to only specific shot shape
        shot_shape_df <- filter(df_driver_ranged, side_class_acc == side & height_class_acc == height)
        
        # Store club and shot shape
        df_ideal_driver_ranged[row, "Club"] <- "Driver"
        df_ideal_driver_ranged[row, "Height_Class"] <- height
        df_ideal_driver_ranged[row, "Side_Class"] <- side
        
        # Get ideal parameters from medians
        df_ideal_driver_ranged[row, "Club_Path_Angle"] <- mean(shot_shape_df$`Club Path`)
        df_ideal_driver_ranged[row, "Lie_Angle"] <- mean(shot_shape_df$`Swing Plane`)
        df_ideal_driver_ranged[row, "Attack_Angle"] <- mean(shot_shape_df$`Attack Angle`)
        df_ideal_driver_ranged[row, "Club_Speed"] <- mean(shot_shape_df$`Club Speed`)
        df_ideal_driver_ranged[row, "Shaft_Lean"] <- mean(shot_shape_df$shaft_lean)
        df_ideal_driver_ranged[row, "Face_Angle"] <- mean(shot_shape_df$`Face Angle`)
        
        # Iterate to next row
        row = row + 1
    }
}

# Show data frame with ideal parameters
df_ideal_driver_ranged
```


